controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

HelloCtrl:
    path: /bonjour
    controller : App\Controller\HelloCtrl::sayHello
HelloCtrlName:
    path: /bonjour/{name}
    controller : App\Controller\HelloCtrl::sayHelloUtil

